<?php

/**
 * Implements hook_menu().
 */
function ak_hello_world_menu() {

    $items['my-first-page'] = array(
        'title' => 'My First Page',
        'page callback' => 'ak_hello_world_my_first_page_content',
        'access callback' => TRUE,
        'menu_name' => 'main-menu',
        'file' => 'ak_hello_world.pages.inc',
        'options' => array('attributes' => array('class' => array('test-class'))),
    );

    return $items;
}
