<?php

/**
 * @file
 * Page with form.
 */

/**
 * Implements hook_menu().
 */
function ak_contact_menu() {

  $items['contact/ajax'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ak_contact_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Page callback: ak page form settings.
 */
function ak_contact_form($form, &$form_state) {

  drupal_add_js(drupal_get_path('module', 'ak_contact') . '/js/cleanForm.js', 'file');
  $form['#attributes'] = array('class' => array('form-class'));
  $form['username'] = array(
    '#type' => 'textfield',
    '#title' => t("Username"),
    '#default_value' => '',
    '#size' => 30,
    '#maxlength' => 30,
    '#required' => TRUE,
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t("Email"),
    '#default_value' => '',
    '#size' => 30,
    '#maxlength' => 30,
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Subscribe'),
    '#ajax' => array(
      'callback' => 'ak_contact_ajax_submit',
      'wrapper' => 'demo-demo-form',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );
  return $form;
}

/**
 * Ajax callback function.
 */
function ak_contact_ajax_submit($form, $form_state) {
  module_load_include('pages.inc', 'user');
  list($form, $form_state) = ajax_get_form();
  watchdog(
    'ak_contact',
    'Name: @name, Email: @email',
    array('@name' => $form_state['input']['username'], '@email' => $form_state['input']['email'])
  );

  drupal_process_form($form['#form_id'], $form, $form_state);

  $commands = array();
  $commands[] = ajax_command_alert('Your data have been saved, check logs');
  $commands[] = array(
    'command' => 'clean_form',
  );

  return array('#type' => 'ajax', '#commands' => $commands);
}
