<?php

/**
 * @file
 * Page show 5 nods.
 */

/**
 * Implements hook_menu().
 */
function ak_page_5_nods_menu() {
  $items['5-nods'] = array(
    'title' => 'Page with 5 nods',
    'page callback' => 'get_5_book_callback',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ak_page_5_nods_theme() {
  return array(
    'ak_page_5_nodes' => array(
      'variables' => array(
        'body' => NULL,
      ),
      'template' => 'ak_page_5_nodes',
    ),
  );
}

/**
 * Page callback.
 */
function get_5_book_callback() {
  $nodes = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('n.type', 'book')
    ->range(0, 5)
    ->execute()
    ->fetchAllAssoc('nid');
  return
    theme('ak_page_5_nodes', array('nodes' => $nodes));
}
