<?php

/**
 * @file
 * Page with form.
 */

/**
 * Implements hook_form_id_alter().
 */
function ak_phone_form_book_node_form_alter(&$form, &$form_state, $form_id) {
  $form['phone'] = array(
    '#type' => 'textfield',
    '#title' => t("Phone number"),
    '#default_value' => ak_phone_get_number(),
    '#size' => 30,
    '#maxlength' => 30,
    '#required' => TRUE,
    '#description' => '12 digits',
  );
  $form['#validate'][] = 'ak_phone_form_validate';
}

/**
 * Implements hook_form_validate().
 */
function ak_phone_form_validate(&$form, &$form_state) {
  if (!preg_match('/^\+375(29|25|44|33)(\d{7})/', $form_state['values']['phone'])) {
    form_set_error('phone', 'Number is not valid');
  }
}

/**
 * Get phone number of current node.
 */
function ak_phone_get_number() {
  $nid = 0;
  if (is_numeric(arg(1))) {
    $nid = arg(1);
  }
  $result = db_select('ak_phone_table', 'c')
    ->fields('c', array('nid', 'number'))
    ->condition('c.nid', $nid)
    ->execute()
    ->fetchAssoc();
  return '+' . $result['number'];
}

/**
 * Implements hook_form_alter().
 */
function ak_phone_node_insert($node) {
  db_insert('ak_phone_table')
    ->fields(array(
      'nid' => $node->nid,
      'number' => mb_substr($node->phone, 1),
    ))
    ->execute();
}

/**
 * Implements hook_node_update().
 */
function ak_phone_node_update($node) {
  $result = db_select('ak_phone_table', 'c')
    ->fields('c', array('nid'))
    ->condition('c.nid', $node->nid)
    ->execute()
    ->fetchCol();
  if (empty($result)) {
    ak_phone_node_insert($node);
  }
  else {
    db_update('ak_phone_table')
      ->fields(array('number' => mb_substr($node->phone, 1)))
      ->condition('nid', $node->nid)
      ->execute();
  }
}

/**
 * Implements hook_node_delete().
 */
function ak_phone_node_delete($node) {
  db_delete('ak_phone_table')
    ->condition('nid', $node->nid)
    ->execute();
}
