<?php

/**
 * @file
 * Page show to manager on even minutes.
 */

/**
 * Implements hook_menu().
 */
function ak_manager_page_menu() {

  $items['check_credentials'] = array(
    'title' => 'Manager page',
    'page callback' => 'ak_manager_page_content',
    'access callback' => 'ak_manager_page_check_role',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback.
 */
function ak_manager_page_content() {
  return 'Even manager or Odd authenticated user';
}

/**
 * Access callback.
 */
function ak_manager_page_check_role() {
  global $user;
  $minute = format_date(time(), 'custom', 'i');
  // Here we check if user is manager and minute is even number.
  if (in_array('manager', $user->roles) && $minute % 2 == 0) {
    return TRUE;
  }
  // Here we check if user is authenticated and minute is odd number.
  if (in_array('authenticated user', $user->roles) && $minute % 2 == 5) {
    return TRUE;
  }
  return FALSE;
}
