<?php

/**
 * @file
 * Page.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function bdyax_test_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }

  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Delete {system} records for long-lost modules.
 */
function bdyax_test_update_7212() {
  $modules = array(
    'field_example',
  );
  db_delete('system')
    ->condition('name', $modules, 'IN')
    ->condition('type', 'module')
    ->execute();
}
